### PR TITLE
 Action server for spline motions 

### PR DESCRIPTION
**Pull request by exo-core**
Implemented and tested the ROS action interface for executing spline motions. It works fine so far but it seems that something is messed up with the initialization of the control mode... I always have to run one SmartServo motion before I can successfully start executing `POINT_TO_POINT_SPLINE` motions. I assume the problem also applies for all other `POINT_TO_POINT` motion types...

### CODE REVIEW

**Comment by exo-core** [comment]
Some details on the added commits:

* Workaround for initialization of PTP motions: Basically I just sitch the controll mode to SmartServoLin and back before starting a PTP motion... it's quite ugly but it works fine^^
* Replaced the `PTPGoalReachedListener` thread by a callback method, which works way more reliable now :-)
* New `MoveAsyncErrorHandler` captures Exceptions thrown in `moveAsync` motions. It prints the error to console and pauses the Sunrise application.
* Moved the logic for applying speed limitations to `SpeedLimits.java`
* New service interfaces to set the speed limits for PTP motions, as they are somewhat different from the ones used by SmartServo. The old services have been renamed to `SetSmartServoJointSpeedLimits` and `SetSmartServoLinSpeedLimits`.
* Made sure that all service calls take speed values in ROS standard units (`m/s`, `m/s^2` or `m/s^3`)

**Comment by exo-core** [comment]
Hi Salvo,
I'll try to come up with some example for a spline motion. However I got some issues, since I pulled the latest changes from the `development` branch. As soon as I start ROSSmartServo the application crashes with some `SAXParserFactory cannot be found` error:

Screenshot from 2019-05-21 19-35-25

Any clue what might be the issue?

**Comment by SalvoVirga** [comment]
Argh! Somehow the Jar file xml-apis-1.0.b2.jar came back to the repo while merging some very old PR...
Removing it (also from the Java build path) will most probably fix that!

**Comment by exo-core** [comment]
Yes, works now :-)

**Comment by exo-core** [comment]
So, another seven commits later:

- I added a way to set the current log level, so that we don't need to wrap every single print command in `if(debug) { ... }` (and it also works outside of the `ROSBaseApplication` class)
- Fixed the `setEndpointFrame` service
- Adopted the `MoveAsyncErrorHandler` (as the action already gets marked as failed in the new `PTPMotionFinishedEventListener`)
- Created a [spline motion demo](https://github.com/exo-core/iiwa_stack_examples/blob/development/iiwa_actions/src/SplineMotionDemo.cpp) that can be found on [my fork](https://github.com/exo-core/iiwa_stack_examples) of [iiwa_stack_examples](https://github.com/SalvoVirga/iiwa_stack_examples). Sidenote: the original examples don't compile with the development branch anymore....
- Using the `PTP` interface to execute `MoveToJointPosition` actions instead of a `SmartServo` command
- Figured out that the following new additions in `disableSmartServo(...)` in `ControlModeHandler.java` break all `PTP` motions, so I commented them out:
  ```
  /*if (!(currentControlMode instanceof PositionControlMode)) {
    changeSmartServoControlMode(motion, new PositionControlMode(true));
  }*/`
  ```
- I also notice that SmartServoLin commands don't do anything anymore (tested with Sunrise 1.16). As I did not change anything there, I believe that they are broke on the `development` branch in general. Can anyone confirm this issue?

**Comment by SalvoVirga** [comment]
> I also notice that SmartServoLin commands don't do anything anymore (tested with Sunrise 1.16). As I did not change anything there, I believe that they are broke on the development branch in general. Can anyone confirm this issue?

There was a small error when setting the speed limits for SmartServoLin motions, now fixed!

**Comment by exo-core** [comment]
Perfect! :-) Does the `spline_motion_demo` work for you?

**Comment by SalvoVirga** [comment]
works great!

Only one question about the changes in `disableSmartServo(...) `in `ControlModeHandler.java` that you mention above. With those lines uncommented the spline demo works, can you give me an example that doesn't when those lines are there? I would like to keep them, maybe one can skip that call to `changeSmartServoControlMode` if `currentControlMode` is null?

**Comment by exo-core** [comment]
For me none of the action interfaces worked anymore with those lines enabled, so you should be able to reproduce the problem by simply using the spline demo.

**Comment by SalvoVirga** [comment]
I just pushed some minor changes and reverted that one for the moment, the spline demo works for me also with those lines. I tried to run it directly and also after moving the robot using a SmartServoLin motion.
Can you check if it still fails for you please?

I also added the option to activate and deactivate debug outputs from the `Process Data` on the `SmartPad`, now the `RoboticsAPI.data.xml` file should contain:

```xml
<processDataContainer>
        <processData dataType="java.lang.String" defaultValue="iiwa" displayName="Robot Name" editableOnHmi="true" id="robot_name" value="iiwa"/>
        <processData dataType="java.lang.String" defaultValue="172.31.1.150" displayName="ROS Master IP" editableOnHmi="true" id="master_ip" value="172.31.1.150"/>
        <processData dataType="java.lang.String" defaultValue="11311" displayName="ROS Master Port" editableOnHmi="false" id="master_port" value="11311"/>
        <processData dataType="java.lang.String" defaultValue="172.31.1.147" displayName="Robot IP" editableOnHmi="false" id="robot_ip" value="172.31.1.147" visibleOnHmi="false"/>
        <processData dataType="java.lang.Boolean" defaultValue="false" displayName="Enable NTP" editableOnHmi="true" id="ntp" value="false"/>
        <processData dataType="java.lang.Boolean" defaultValue="false" displayName="Enable Debug Output" editableOnHmi="true" id="debug" value="false"/>
</processDataContainer>
```

**Comment by exo-core** [comment]
I'll give it I try when I'm in the lab tomorrow.

**Comment by exo-core** [comment]
Hi @SalvoVirga,

I just ran some tests in the lab and was not able to reproduce the problem anymore. Probably the check of `currentControlMode` did the trick. 

It should be safe to merge all of this now. :smile: I believe this will then also resolve the issues with the action in #162 and #174.

**Pull request merged**
