### PR TITLE
Add "hardare_interface" as Gazebo was complaining.

### PR DESCRIPTION
**Pull request by DavidWuthier**
Fix the "deprecated syntax" warning.

### CODE REVIEW

**Comment by SalvoVirga** [comment]
Thanks for the contribution!
Is this marked as deprecated in kinetic? I will check everything better in a couple of weeks (and also fix the travis build), I'm away from office atm.

**Comment by DavidWuthier** [comment]
You're welcome!
As below, it doesn't tell about kinetic, but from what I remember, it's not a problem on Indigo.
Thanks

[ WARN] [1506328417.325478922, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_1'.
[ WARN] [1506328417.326840005, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_2'.
[ WARN] [1506328417.328747125, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_3'.
[ WARN] [1506328417.329799199, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_4'.
[ WARN] [1506328417.330598224, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_5'.
[ WARN] [1506328417.331336763, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_6'.
[ WARN] [1506328417.332273308, 0.158000000]: Deprecated syntax, please prepend 'hardware_interface/' to 'PositionJointInterface' within the <hardwareInterface> tag in joint 'iiwa_joint_7'.

**Comment by matthiashh** [comment]
Is there any reason this is not merged?

I applied the patch to the `development` branch with `melodic` and it works.

**Comment by SalvoVirga** [comment]
> Is there any reason this is not merged?
> 
> I applied the patch to the `development` branch with `melodic` and it works.

Mainly only cause at the time the CI was buggy and checks did not run properly. I could merge it to `master` but I will manually patch `development` since it diverged to much from `master` already. Before the end of the month I plan to release a new version based on `development` anyhow.

**Pull request merged**
