### PR TITLE
[WIP] Development

### PR DESCRIPTION
**Pull request by exo-core**
This is a collection of all the changes I have done in the last months, including

- TF support for Cartesian Motion
- ROS Action support
- Interface for adding tools specific ROS communication

I merged with the lasted changes from the development branch, but I must admit I did not have the possibility to test the merged code yet.
This also contains still quite some debug output.

I will update the MR after testing.

### CODE REVIEW

**Comment by SalvoVirga** [comment]
Looks great already! I'll fix the travis build asap, be sure to merge that.
I might have some questions, but now that I understood you are not very far from us, shouldn't we maybe plan a meeting in Garching?

**Comment by exo-core** [comment]
Hi @SalvoVirga,
sure we can do that. I just came back from a business trip yesterday and I have a little to catch up, but anytime next week should be fine for me ;-)

**Comment by exo-core** [comment]
I just tested the merged version and it seems to run fine :-)

**Comment by SalvoVirga** [comment]
Very good! I'm extremely busy before my Christmas vacation, but in early January I would like to push the merge of this and a new release.
What is needed is to have the new functionalities documented in the wiki, so that their usage is clear.
I will send you an email to set up a meeting in January and get things done! :)

**Pull request merged**
